config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  root to: "application#dashboard"

  # Mount this at a hard-to-guess URL
  mount Resque::Server.new, at: "/resque-c08cb17ca6581cbcad1501a7da7e8579"

  # --- NON-LOGGED-IN USERS ---

  get :sign_up, to: "registrations#new"
  post :sign_up, to: "registrations#create", as: :account_registration
  get :sign_up,  to: "registrations#new", as: :new_account_registration

  get :sign_in, to: "sessions#new", as: :new_account_session
  post :sign_in, to: "sessions#create", as: :account_session
  delete :sign_out, to: "sessions#destroy", as: :destroy_account_session

  post 'accounts/password',     to: 'passwords#create', as: :account_password
  get 'accounts/password/new',  to: 'passwords#new',    as: :new_account_password
  get 'accounts/password/edit', to: 'passwords#edit',   as: :edit_account_password
  put   'accounts/password',    to: 'passwords#update'
  patch 'accounts/password',    to: 'passwords#update'

  # --- EVERYBODY ---

  resources :airports, only: [] do
    collection { get :typeahead }
  end

  Destination::TYPES.each do |type|
    # /airports, /cities, /countries, /regions
    get type.pluralize, to: "destinations##{type}"
  end

  post :support, to: 'support#support'

  controller :static_pages do
    get :privacy_policy
    get :terms_and_conditions
    get :contact_us
  end

  # --- LOGGED IN ACCOUNTS ---

  resource :account, only: [:edit, :update] do
    get  :type
    post :type, action: :submit_type
  end

  resources :balances

  resources :card_recommendations do
    member do
      get   :click
      patch :decline
    end
  end

  resources :card_accounts, except: :index
  resources :cards, only: :index

  get  "eligibility/survey", to: "eligibilities#survey", as: :survey_eligibility
  post "eligibility/survey", to: "eligibilities#save_survey"

  get "estimates/:from_code/:to_code/:type/:no_of_passengers", to: "estimates#get"

  namespace :integrations do
    get 'award_wallet/settings'
    namespace :award_wallet do
      get :callback
      get :poll
      get :sync
      get :syncing
      get :survey
      post :survey, action: :save_survey

      resources :owners, only: [] do
        member do
          patch :update_person
        end
      end

      resources :accounts
    end
  end

  get 'auth/facebook/callback', to: 'integrations/facebook#callback'

  resources :interest_regions, only: [], path: "regions_of_interest" do
    collection do
      get  :survey
      post :survey, action: :save_survey
    end
  end

  resources :home_airports do
    collection do
      get  :edit
      post :overwrite
      get  :survey
      post :survey, action: :save_survey
    end
  end

  resources :notifications, only: :show

  resources :people, only: [] do
    resources :balances, only: [] do
      collection do
        get  :survey
        post :survey, action: :save_survey
      end
    end
    resources :cards, only: [] do
      collection do
        get  :survey
        post :survey, action: :save_survey
      end
    end
    resource :spending_info, path: :spending, only: [:edit, :update] do
      member do
        patch :confirm
      end
    end
  end

  resource :phone_number, only: [:new, :create] do
    post :skip
  end

  resources :card_products, only: [] do
    resources :card_accounts, only: [:new, :create]
  end

  resource :readiness, only: [:edit, :update] do
    collection do
      get  :survey
      post :survey, action: :save_survey
    end
  end

  resource :recommendation_requests

  get :slack, to: "slack_invites#new"
  post "slack/invite", to: "slack_invites#create"

  resource :spending_info, path: :financials, only: [:show] do
    get :survey
    post :survey, action: :save_survey
  end

  resources :travel_plans do
    collection do
      patch :skip_survey
    end
  end

  # ---- ADMINS -----

  # This method is necessary to get the 'authenticate_admin!' method
  # in the controllers

  get 'admin/sign_in', to: 'admin_area/sessions#new', as: :new_admin_session
  post 'admin/sign_in', to: 'admin_area/sessions#create', as: :admin_session
  delete 'admin/sign_out', to: 'admin_area/sessions#destroy',
    as: :destroy_admin_session

  namespace :admin, module: :admin_area do
    resources :accounts, only: [:index] do
      collection do
        get :search
      end
      member do
        get :inspect
      end
    end
    resources :admins
    resources :banks, only: [:index]
    resources :card_products, except: :destroy do
      collection do
        get :images
      end
      resources :offers, only: [:index, :create, :new]
    end

    resources :card_accounts, only: [:edit, :update]
    resources :currencies

    # show and edit redirect to the nested action:
    resources :offers, only: [:show, :edit, :index, :update] do
      member do
        patch :kill, :replace, :unkill, :verify
      end
    end
    resources :destinations, only: :index
    Destination::TYPES.each do |type|
      # /airports, /cities, /countries, /regions
      get type.pluralize, to: "destinations##{type}"
    end
    resources :people, only: :show do
      resource :spending_info
      resources :card_accounts
      resources :card_recommendations, only: [:create, :edit, :update] do
        collection do
          post :complete
        end
      end
    end
    resources :card_recommendations
    resources :recommendation_notes, only: [:edit, :update]
    resources :recommendation_requests
    resource :registration
    resources :travel_plans, only: [:edit, :update]
  end

  # ---- /ADMINS -----
end

app/models/survey.rb
class Survey < ApplicationRecord

  # Attributes

  enum citizenship:  [ :us_citizen, :us_permanent_resident, :neither]
  # Don't use 'no' as a value because it messes up i18n.t
  enum has_business: [ :no_business, :with_ein, :without_ein ]

  def full_name
    [first_name, middle_names, last_name].compact.join(" ")
  end

  alias :has_business_with_ein? :with_ein?
  alias :has_business_without_ein? :without_ein?

  def has_business?
    has_business_with_ein? || has_business_without_ein?
  end

  def complete?
    persisted? && has_added_cards? && has_added_balances?
  end


  # Validations

  MINIMUM_CREDIT_SCORE = 350
  MAXIMUM_CREDIT_SCORE = 850

  VALID_TIME_ZONES = ActiveSupport::TimeZone.all.map(&:name)

  validates :account, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  validates :time_zone,
    inclusion: { in: VALID_TIME_ZONES },
    presence: true
  validates :credit_score, presence: true,
    numericality: {
      greater_than_or_equal_to: MINIMUM_CREDIT_SCORE,
      less_than_or_equal_to:    MAXIMUM_CREDIT_SCORE,
      # avoid duplicate error message (from presence validation) when nil:
      allow_nil: true
    }
  # Spending columns = spending per month, in whole US dollars
  validates :personal_spending,
    presence: true,
    numericality: {
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: POSTGRESQL_MAX_INT_VALUE,
      # avoid duplicate error message (from presence validation) when nil:
      allow_nil: true
    }
  validates :business_spending,
    presence: true,
    numericality: {
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: POSTGRESQL_MAX_INT_VALUE,
      # avoid duplicate error message (from presence validation) when nil:
      allow_nil: true
    }

  # Associations

  belongs_to :account

  # Callbacks

  auto_strip_attributes :first_name, :middle_names, :last_name, :phone_number

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable, :confirmable

  # Attributes

  delegate :business_spending, :citizenship, :credit_score, :first_name,
      :full_name, :has_business, :has_business?, :has_business_with_ein?,
      :has_business_without_ein?, :has_added_balances, :has_added_balances?,
      :has_added_cards, :has_added_cards?, :imessage, :imessage?, :last_name,
      :middle_names, :personal_spending, :phone_number, :text_message,
      :text_message?, :time_zone, :whatsapp, :whatsapp?, :will_apply_for_loan,
    to: :survey, allow_nil: true

  def name
    survey.present? ? survey.full_name : "#{self.class} ##{id}"
  end

  def has_completed_main_survey?
    !!survey.try(:persisted?)
  end

  def survey_complete?
    !!survey.try(:complete?)
  end

  # Validations

  validates :survey, associated: true

  # Associations

  has_many :card_accounts
  has_many :card_recommendations, -> { recommendations },
                                  class_name: "CardAccount"
  has_many :cards, through: :card_accounts
  has_many :travel_plans

  has_one :survey

  has_many :balances
  has_many :currencies, through: :balances

  # Scopes

  scope :admin, -> { where(admin: true) }
  scope :non_admin, -> { where(admin: false) }

  scope :onboarded, -> do
    non_admin.joins(:survey).where(
      surveys: { has_added_cards: true, has_added_balances: true }
    )
  end
end

app/helpers/survey_helper.rb
module SurveyHelper
  def has_business_label_text(value)
    case value
    when "with_ein"
      "Yes, and I have an EIN (Employer ID Number)"
    when "without_ein"
      "Yes, but I do not have an EIN - I am a freelancer or sole proprietor"
    when "no_business"
      "I do not own a business"
    end
  end
end

app/views/survey/balances.html.erb
<h1>Balances</h1>

<p>Do you have any existing frequent flyer mile balances?</p>

<%= form_tag survey_balances_path do %>
  <div class="balances_survey">
    <% @currencies.each do |currency| %>
      <div
        id="<%= dom_id(currency) %>"
        class="<%= dom_class(currency) %> survey_currency checkbox"
      >
        <label>
          <%= currency_balance_checkbox(currency) %>
          <%= currency.name %>
        </label>

        <%= currency_balance_value_field(currency) %>
      </div>
    <% end %>
  </div>

  <%= submit_tag "Submit", class: "btn btn-primary" %>
<% end %>

app/views/survey/card_accounts.html.erb
<% provide :title, "Survey - Cards" %>

<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">
    <h1>Your Cards</h1>

    <p>Before we can recommend you a credit card to apply for, we need to
      know which cards you already have.</p>

    <p>Please select <strong>all</strong> of the credit/debit cards below for which you have been the <strong>primary cardholder in the past 24 months</strong>.</p>

    <p>
      For this question, you <strong>should</strong> include:
      <ul>
        <li>Accounts that are currently open.</li>
        <li>
          Accounts that were opened in the last 24 months, but are now closed.
        </li>
        <li>
          Accounts that were opened in the last 24 months, but have been changed
          into another type of card.
        </li>
      </ul>
    </p>

    <p>
      Please <strong>do not</strong> include:
      <ul>
        <li>
          Cards for which you were not the primary cardholder.
          <br />
          <i>
            Example: Your spouse added you as an additional cardholder on his or
            her account.
          </i>
        </li>
        <li>
          Any card you opened more than 24 months ago that is not currently open.
          <br />
          <i>
            Example: You opened a card 3 years ago, and you closed the account
            yesterday.
          </i>
        </li>
      </ul>
    </p>

    <%= form_tag survey_card_accounts_path do %>
      <% @cards.group_by(&:bank).each do |bank, cards_for_1_bank| %>

        <div id="<%= bank %>_cards">

          <% cards_for_1_bank.group_by(&:bp).each do |bp, cards| %>

            <div id="<%= bank %>_<%= bp %>_cards">
              <h3><%= cards.first.bank_name %> <%= bp.capitalize %> Cards</h3>

              <div class="row">

                <%= collection_check_boxes :card_account, :card_ids, cards,
                                                          :id, :name do |cb| %>
                  <div class="card-survey-checkbox">
                    <%= card_image_tag(cb.object) %>
                    <div>
                      <%= cb.check_box %>
                      &nbsp;
                      <%= cb.label %>
                    </div>
                  </div>

                <% end %>

              </div><!-- .row -->
            </div><!-- #cards_onboarding_<%= bank %>_<%= bp %> -->

          <% end # cards_for_1_bank.group_by(&:bp).each %>

        </div><!-- #cards_onboarding_<%= bank %> -->

      <% end # @cards.group_by(&:bank).each %>

      <%= submit_tag "Save", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/survey/new_balances.html.erb
<h1>Balances</h1>

<p>
  <%= @name.does.capitalize %> <%= @name.name %> have any existing frequent
  flyer mile balances?
</p>

<% if @survey.errors %>
  <div class="alert alert-danger">
    Could not save your balances:

    <ul>
      <% @survey.errors.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_tag survey_balances_path(params[:passenger]) do %>
  <div class="balances_survey">
    <% @survey.balances.each do |balance| %>
      <% currency = balance.currency %>
      <div
        id="<%= dom_id(currency) %>"
        class="<%= dom_class(currency) %> survey_currency checkbox"
      >
        <label>
          <%= currency_balance_checkbox(balance) %>
          <%= currency.name %>
        </label>

        <%= currency_balance_value_field(balance) %>
      </div>
    <% end %>
  </div>

  <%= submit_tag "Submit", class: "btn btn-primary" %>
<% end %>

app/views/survey/new_card_accounts.html.erb
<% provide :title, "Survey - Cards" %>

<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">
    <h1><%= @name.possessive.capitalize %> Cards</h1>

    <p>
      Before we can recommend <%= @name.name %> a credit card to apply for, we
      need to know which cards <%= @name.he_she %> already <%= @name.has %>.
    </p>

    <p>
      Please select <strong>all</strong> of the credit/debit cards below for
      which <%= @name.name %> <%= @name.has %> been the <strong>primary
      cardholder in the past 24 months</strong>.
    </p>

    <p>
      For this question, you <strong>should</strong> include:
      <ul>
        <li>Accounts that are currently open.</li>
        <li>
          Accounts that were opened in the last 24 months, but are now closed.
        </li>
        <li>
          Accounts that were opened in the last 24 months, but have been
          changed into another type of card.
        </li>
      </ul>
    </p>

    <p>
      Please <strong>do not</strong> include:
      <ul>
        <li>
          Cards for which <%= @name.name %> <%= @name.was %> not the primary
          cardholder.
          <br />
          <i>
            Example: Your spouse added you as an additional cardholder on his or
            her account.
          </i>
        </li>
        <li>
          Any card <%= @name.name %> opened more than 24 months ago that is
          not currently open.
          <br />
          <i>
            Example: You opened a card 3 years ago, and you closed the account
            yesterday.
          </i>
        </li>
      </ul>
    </p>

    <%= form_tag survey_card_accounts_path(params[:passenger]) do %>
      <% @cards.group_by(&:bank).each do |bank, cards_for_1_bank| %>
        <div id="<%= bank.to_param %>_cards">

          <% cards_for_1_bank.group_by(&:bp).each do |bp, cards| %>

            <div id="<%= bank.to_param %>_<%= bp %>_cards">
              <h3><%= bank.name %> <%= bp.capitalize %> Cards</h3>

              <div class="row">
                <%= collection_check_boxes(
                    :card_account,
                    :card_ids,
                    cards,
                    :id,
                    :name
                ) do |cb| %>
                  <div id="<%= dom_id(cb.object) %>" class="card-survey-checkbox">
                    <%= card_image_tag(cb.object) %>
                    <div>
                      <div><%= cb.check_box %></div>
                      <div><%= cb.label %></div>
                    </div>
                  </div>

                <% end %>

              </div><!-- .row -->
            </div><!-- #cards_onboarding_<%= bank.to_param %>_<%= bp %> -->

          <% end # cards_for_1_bank.group_by(&:bp).each %>

        </div><!-- #cards_onboarding_<%= bank.to_param %> -->

      <% end # @cards.group_by(&:bank).each %>

      <%= submit_tag "Save", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/survey/new_travel_plan.html.erb
<h1>Add a Travel Plan</h1>

<p>
  Where do you want to go, and when? Let us know your travel plans and
  we'll help you get a great deal on the flight.
</p>

<%= render "shared/model_validation_errors", model: @survey %>

<%= form_for @survey, url: request.path, as: :travel_plan do |f| %>

  <div class="form-inline">
    <% @survey.class.types.each do |type, _| %>
      <div class="form-group">
        <label>
          <%= type.capitalize %>
          &nbsp;
          <%= f.radio_button(
            :type,
            type,
            checked: type == f.object.type
          ) %>
        </label>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="form-group col-xs-12 col-md-6">
      <%= f.label :from %>
      <%= f.collection_select(
        :from_id,
        @countries,
        :id,
        :name,
        prompt: "Select a country of origin"
      ) %>
    </div>

    <div class="form-group col-xs-12 col-md-6">
      <%= f.label :to %>
      <%= f.collection_select(
        :to_id,
        @countries,
        :id,
        :name,
        prompt: "Select a destination country"
      ) %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-xs-12 col-md-6">
      <%= f.label        :no_of_passengers, "# of passengers" %>
      <%= f.number_field :no_of_passengers,
                            min: 1, max: TravelPlan::MAX_FLIGHTS %>
    </div>

    <div class="form-group col-xs-12 col-md-6">
      <%= f.label      :earliest_departure %>
      <%= f.text_field :earliest_departure %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-6">
      <label>What class(es) of service would you consider for this trip?</label>

      <div class="form-inline">
        <div class="radio">
          <%= f.label :will_accept_economy do %>
            <%= f.check_box :will_accept_economy %>
            &nbsp;Economy&nbsp;
          <% end %>
        </div>

        <div class="radio">
          <%= f.label :will_accept_premium_economy do %>
            <%= f.check_box :will_accept_premium_economy %>
            &nbsp;Premium Economy&nbsp;
          <% end %>
        </div>

        <div class="radio">
          <%= f.label :will_accept_business_class do %>
            <%= f.check_box :will_accept_business_class %>
            &nbsp;Business Class&nbsp;
          <% end %>
        </div>

        <div class="radio">
          <%= f.label :will_accept_first_class do %>
            <%= f.check_box :will_accept_first_class %>
            &nbsp;First Class&nbsp;
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-md-6">
      <div class="form-group">
        <%= f.text_area(
          :further_information,
          placeholder: "Optional: give us any extra information about your travel plans that you think might be relevant"
        ) %>
        <span id="travel_plan_further_information_counter"></span>
      </div>
    </div>
  </div>

  <%= f.submit "Save", class: "btn-primary" %>

<% end %>

app/views/survey/user_info.html.erb
<% provide(:title, "Survey - Contact and Spending Info") %>

<h1>Contact Info</h1>

<%= render "shared/model_validation_errors", model: @user_info %>

<p>Thanks for signing up to Abroaders! Before we can get started, we need
  some information from you.</p>

<%= form_for @user_info, url: survey_user_info_path do |f| %>

  <%# TODO add 'required' star %>

  <% %i[first_name middle_names last_name phone_number].each do |attr| %>
    <div class="form-group required">
      <%= f.label attr %>
      <%= f.text_field attr %>
    </div>
  <% end %>

  <p>Which of the following are you capable of receiving at this number?</p>

  <div class="form-inline">
    <div class="checkbox">
      <%= f.label :text_message do %>
        <%= f.check_box :text_message %>
        Text Message
      <% end %>
    </div>
    &nbsp;
    <div class="checkbox">
      <%= f.label :whatsapp do %>
        <%= f.check_box :whatsapp %>
        WhatsApp
      <% end %>
    </div>
    &nbsp;
    <div class="checkbox">
      <%= f.label :imessage do %>
        <%= f.check_box :imessage %>
        iMessage
      <% end %>
    </div>
  </div>

  <div class="form-group required">
    <%= f.label :time_zone %>
    <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {},
      # For some reason I can't get time_zone_select to add the BS class
      # manually like I can with the overriden methods:
            class: BootstrapOverrides::Overrides::BOOTSTRAP_CLASS %>
  </div>

  <div class="form-group">
    <%= f.label :citizenship %>

    <% UserInfo.citizenships.each do |name, _| %>
      <div class="radio">
        <label>
          <%= f.radio_button(
                :citizenship,
                name,
                checked: f.object.citizenship == name
              ) %>
          <%= t("activerecord.attributes.user_info.citizenships.#{name}") %>
        </label>
      </div>
    <% end %>
  </div>

  <h1>Spending Info</h1>

  <div class="form-group">
    <%= f.label :credit_score %>

    <p class="help-block">
      Your credit score should be a number between
      <%= UserInfo::MINIMUM_CREDIT_SCORE %> and
      <%= UserInfo::MAXIMUM_CREDIT_SCORE %>
    </p>

    <%= f.number_field :credit_score %>
  </div>

  <div class="form-group">
    <%= f.label :will_apply_for_loan %>
    <div class="radio">
      <label>
        <%= f.radio_button(
              :will_apply_for_loan,
              true,
              checked: f.object.will_apply_for_loan
            ) %>
        Yes
      </label>
    </div>

    <div class="radio">
      <label>
        <%= f.radio_button(
              :will_apply_for_loan,
              false,
              checked: !f.object.will_apply_for_loan
            ) %>
        No
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :personal_spending %>

    <div class="input-group">
      <div class="input-group-addon">$</div>
      <%= f.number_field :personal_spending %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :has_business %>

    <% UserInfo.has_businesses.each do |name, _| %>
      <div class="radio">
        <label>
          <%= f.radio_button(
                :has_business,
                name,
                checked: f.object.has_business == name
              ) %>
          <%= t("activerecord.attributes.user_info.has_businesses.#{name}") %>
        </label>
      </div>
    <% end %>
  </div>

  <div
    id="business_spending_form_group"
    class="form-group"
    style="display:none"
  >
    <%= f.label :business_spending %>

    <div class="input-group">
      <div class="input-group-addon">$</div>
      <%= f.number_field :business_spending %>
    </div>
  </div>

  <br>

  <%= f.submit "Save", class: "btn btn-primary" %>

<% end %>