config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  root to: "application#dashboard"

  # Mount this at a hard-to-guess URL
  mount Resque::Server.new, at: "/resque-c08cb17ca6581cbcad1501a7da7e8579"

  # --- NON-LOGGED-IN USERS ---

  get :sign_up, to: "registrations#new"
  post :sign_up, to: "registrations#create", as: :account_registration
  get :sign_up,  to: "registrations#new", as: :new_account_registration

  get :sign_in, to: "sessions#new", as: :new_account_session
  post :sign_in, to: "sessions#create", as: :account_session
  delete :sign_out, to: "sessions#destroy", as: :destroy_account_session

  post 'accounts/password',     to: 'passwords#create', as: :account_password
  get 'accounts/password/new',  to: 'passwords#new',    as: :new_account_password
  get 'accounts/password/edit', to: 'passwords#edit',   as: :edit_account_password
  put   'accounts/password',    to: 'passwords#update'
  patch 'accounts/password',    to: 'passwords#update'

  # --- EVERYBODY ---

  resources :airports, only: [] do
    collection { get :typeahead }
  end

  Destination::TYPES.each do |type|
    # /airports, /cities, /countries, /regions
    get type.pluralize, to: "destinations##{type}"
  end

  post :support, to: 'support#support'

  controller :static_pages do
    get :privacy_policy
    get :terms_and_conditions
    get :contact_us
  end

  # --- LOGGED IN ACCOUNTS ---

  resource :account, only: [:edit, :update] do
    get  :type
    post :type, action: :submit_type
  end

  resources :balances

  resources :card_recommendations do
    member do
      get   :click
      patch :decline
    end
  end

  resources :card_accounts, except: :index
  resources :cards, only: :index

  get  "eligibility/survey", to: "eligibilities#survey", as: :survey_eligibility
  post "eligibility/survey", to: "eligibilities#save_survey"

  get "estimates/:from_code/:to_code/:type/:no_of_passengers", to: "estimates#get"

  namespace :integrations do
    get 'award_wallet/settings'
    namespace :award_wallet do
      get :callback
      get :poll
      get :sync
      get :syncing
      get :survey
      post :survey, action: :save_survey

      resources :owners, only: [] do
        member do
          patch :update_person
        end
      end

      resources :accounts
    end
  end

  get 'auth/facebook/callback', to: 'integrations/facebook#callback'

  resources :interest_regions, only: [], path: "regions_of_interest" do
    collection do
      get  :survey
      post :survey, action: :save_survey
    end
  end

  resources :home_airports do
    collection do
      get  :edit
      post :overwrite
      get  :survey
      post :survey, action: :save_survey
    end
  end

  resources :notifications, only: :show

  resources :people, only: [] do
    resources :balances, only: [] do
      collection do
        get  :survey
        post :survey, action: :save_survey
      end
    end
    resources :cards, only: [] do
      collection do
        get  :survey
        post :survey, action: :save_survey
      end
    end
    resource :spending_info, path: :spending, only: [:edit, :update] do
      member do
        patch :confirm
      end
    end
  end

  resource :phone_number, only: [:new, :create] do
    post :skip
  end

  resources :card_products, only: [] do
    resources :card_accounts, only: [:new, :create]
  end

  resource :readiness, only: [:edit, :update] do
    collection do
      get  :survey
      post :survey, action: :save_survey
    end
  end

  resource :recommendation_requests

  get :slack, to: "slack_invites#new"
  post "slack/invite", to: "slack_invites#create"

  resource :spending_info, path: :financials, only: [:show] do
    get :survey
    post :survey, action: :save_survey
  end

  resources :travel_plans do
    collection do
      patch :skip_survey
    end
  end

  # ---- ADMINS -----

  # This method is necessary to get the 'authenticate_admin!' method
  # in the controllers

  get 'admin/sign_in', to: 'admin_area/sessions#new', as: :new_admin_session
  post 'admin/sign_in', to: 'admin_area/sessions#create', as: :admin_session
  delete 'admin/sign_out', to: 'admin_area/sessions#destroy',
    as: :destroy_admin_session

  namespace :admin, module: :admin_area do
    resources :accounts, only: [:index] do
      collection do
        get :search
      end
      member do
        get :inspect
      end
    end
    resources :admins
    resources :banks, only: [:index]
    resources :card_products, except: :destroy do
      collection do
        get :images
      end
      resources :offers, only: [:index, :create, :new]
    end

    resources :card_accounts, only: [:edit, :update]
    resources :currencies

    # show and edit redirect to the nested action:
    resources :offers, only: [:show, :edit, :index, :update] do
      member do
        patch :kill, :replace, :unkill, :verify
      end
    end
    resources :destinations, only: :index
    Destination::TYPES.each do |type|
      # /airports, /cities, /countries, /regions
      get type.pluralize, to: "destinations##{type}"
    end
    resources :people, only: :show do
      resource :spending_info
      resources :card_accounts
      resources :card_recommendations, only: [:create, :edit, :update] do
        collection do
          post :complete
        end
      end
    end
    resources :card_recommendations
    resources :recommendation_notes, only: [:edit, :update]
    resources :recommendation_requests
    resource :registration
    resources :travel_plans, only: [:edit, :update]
  end

  # ---- /ADMINS -----
end

app/models/airport.rb
# For future reference, our original list of airports and cities was based on:
#
# https://bitbucket.org/!api/2.0/snippets/georgemillo/y8zMo/8ec4454bc955b27ee278ad92187e046c548312fb/files/snippet.txt
#
# and
#
# https://bitbucket.org/!api/2.0/snippets/georgemillo/Ad9Mb/1852d0a5ba78f4f061d9cd754c02c627b7e643da/files/file
#
# But this original data has been heavily modified (and new entries added.) Our
# current airport data is mostly based on miles.biz's list of airports (as of
# 25/10/2016). Keeping the note of the above links for historical reference.
class Airport < Destination
  IATA_CODE_REGEX = /\A[A-Z]{3}\z/i

  has_and_belongs_to_many :accounts,
                          join_table: :accounts_home_airports,
                          foreign_key: :airport_id

  # Our list of airports is based on data that we got from miles.biz. Note that
  # if the airport name according to miles.biz ended in 'Airport', we've
  # stripped that off the end before saving to our DB. We've also stripped all
  # diacritics (using I18n.transliterate) to e.g. "São Paulo" is saved in our
  # DB as "Sao Paulo"

  validates :parent, presence: true
  validates :code, format: { with: IATA_CODE_REGEX }

  validate :parent_is_correct_type

  # Use alias, not alias_attribute, because alias_attribute adds #city?  which
  # conflicts with a method we already have.
  alias city parent
  alias city= parent=
  delegate :name, to: :city, prefix: true
  delegate :country, to: :city

  def full_name
    if name.downcase.include?(city_name.downcase)
      "#{name} (#{code})"
    else
      "#{city_name} #{name} (#{code})"
    end
  end

  private

  def parent_is_correct_type
    return unless !parent.nil? && !parent.type.nil? && parent.type != "City"
    errors.add(:parent, "must be a city")
  end
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  # 'typeahead' action is required for home airports survey and travel plan
  # to load airport data for the typeahead

  def typeahead
    @airports = Airport.includes(:parent).order(code: :asc)

    respond_to do |format|
      format.json do
        fresh_when last_modified: @airports.maximum(:updated_at),
                   etag: @airports.cache_key
      end
    end
  end
end

app/views/airports/_survey_form.html.erb
<div class="panel-body">
  <%= render "shared/model_validation_errors", model: survey %>
  <p class="helper-message">You can add five airports maximum</p>
  <div class="col-md-9">

    <%= form_for survey_airports_path, html: { class: "home-airport-survey-form text-center" } do |f| %>
      <div class="row">
        <div class="col-xs-12 col-md-4 saved-area">
          <p class="title">Saved home airports:</p>
          <div class="home-airports"></div>
        </div>

        <div class="col-xs-12 col-md-8">
          <div class="alert alert-info info-message"></div>
          <div class="alert alert-danger error-message"></div>
          <div class="row form-group">
            <div class="col-xs-12">
              <%= text_field_tag :typeahead, nil, class: "form-control typeahead", placeholder: "ex. New York or JFK" %>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-12">
              <%= f.button type: "submit", class: "submit-airports-survey form-control btn btn-lg btn-primary", disabled: true do %>
                <i class="fa fa-check" aria-hidden="true"></i>
                Save and continue
              <% end %>
            </div>
          </div>
        </div>
      </div>

    <% end %>
  </div>
</div><!-- .panel-body -->

app/views/airports/index.json.erb
<% cache(@airports) do %>
  <%
    array_for_typeahead = @airports.map do |airport|
      id = airport.id
      name = airport.name
      code = airport.code
      city_name = airport.city_name

      displayed_name = airport.full_name

      {
        id: id,
        code: code,
        name: displayed_name,
        tokens: [code, city_name, "#{city_name} (#{displayed_name})", "#{name} (#{code})"]
      }
    end
  %>
  <%= raw(array_for_typeahead.to_json) %>
<% end %>

app/views/airports/survey.html.erb
<% provide :title, "Add Home Aiports" %>
<% provide :no_sidebar, true unless current_account.onboarded_home_airports? %>

<div class="hpanel home-airports-survey">
  <div class="panel-heading hbuilt">
    <div class="row">
      <div class="col-xs-12 greeting-message">
        <h1>Welcome, traveler!</h1>
        <h2>What's your home airport?</h2>
      </div>
    </div><!-- .row -->
  </div>

  <%= render "airports/survey_form", survey: @survey %>
</div>

app/views/airports/typeahead.json.erb
<% cache(@airports) do %>
  <%
    array_for_typeahead = @airports.map do |airport|
      id = airport.id
      name = airport.name
      code = airport.code
      city_name = airport.city_name

      displayed_name = airport.full_name

      {
        id: id,
        code: code,
        name: displayed_name,
        tokens: [code, city_name, "#{city_name} (#{displayed_name})", "#{name} (#{code})"]
      }
    end
  %>
  <%= raw(array_for_typeahead.to_json) %>
<% end %>