config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  root to: "application#dashboard"

  # Mount this at a hard-to-guess URL
  mount Resque::Server.new, at: "/resque-c08cb17ca6581cbcad1501a7da7e8579"

  # --- NON-LOGGED-IN USERS ---

  get :sign_up, to: "registrations#new"
  post :sign_up, to: "registrations#create", as: :account_registration
  get :sign_up,  to: "registrations#new", as: :new_account_registration

  get :sign_in, to: "sessions#new", as: :new_account_session
  post :sign_in, to: "sessions#create", as: :account_session
  delete :sign_out, to: "sessions#destroy", as: :destroy_account_session

  post 'accounts/password',     to: 'passwords#create', as: :account_password
  get 'accounts/password/new',  to: 'passwords#new',    as: :new_account_password
  get 'accounts/password/edit', to: 'passwords#edit',   as: :edit_account_password
  put   'accounts/password',    to: 'passwords#update'
  patch 'accounts/password',    to: 'passwords#update'

  # --- EVERYBODY ---

  resources :airports, only: [] do
    collection { get :typeahead }
  end

  Destination::TYPES.each do |type|
    # /airports, /cities, /countries, /regions
    get type.pluralize, to: "destinations##{type}"
  end

  post :support, to: 'support#support'

  controller :static_pages do
    get :privacy_policy
    get :terms_and_conditions
    get :contact_us
  end

  # --- LOGGED IN ACCOUNTS ---

  resource :account, only: [:edit, :update] do
    get  :type
    post :type, action: :submit_type
  end

  resources :balances

  resources :card_recommendations do
    member do
      get   :click
      patch :decline
    end
  end

  resources :card_accounts, except: :index
  resources :cards, only: :index

  get  "eligibility/survey", to: "eligibilities#survey", as: :survey_eligibility
  post "eligibility/survey", to: "eligibilities#save_survey"

  get "estimates/:from_code/:to_code/:type/:no_of_passengers", to: "estimates#get"

  namespace :integrations do
    get 'award_wallet/settings'
    namespace :award_wallet do
      get :callback
      get :poll
      get :sync
      get :syncing
      get :survey
      post :survey, action: :save_survey

      resources :owners, only: [] do
        member do
          patch :update_person
        end
      end

      resources :accounts
    end
  end

  get 'auth/facebook/callback', to: 'integrations/facebook#callback'

  resources :interest_regions, only: [], path: "regions_of_interest" do
    collection do
      get  :survey
      post :survey, action: :save_survey
    end
  end

  resources :home_airports do
    collection do
      get  :edit
      post :overwrite
      get  :survey
      post :survey, action: :save_survey
    end
  end

  resources :notifications, only: :show

  resources :people, only: [] do
    resources :balances, only: [] do
      collection do
        get  :survey
        post :survey, action: :save_survey
      end
    end
    resources :cards, only: [] do
      collection do
        get  :survey
        post :survey, action: :save_survey
      end
    end
    resource :spending_info, path: :spending, only: [:edit, :update] do
      member do
        patch :confirm
      end
    end
  end

  resource :phone_number, only: [:new, :create] do
    post :skip
  end

  resources :card_products, only: [] do
    resources :card_accounts, only: [:new, :create]
  end

  resource :readiness, only: [:edit, :update] do
    collection do
      get  :survey
      post :survey, action: :save_survey
    end
  end

  resource :recommendation_requests

  get :slack, to: "slack_invites#new"
  post "slack/invite", to: "slack_invites#create"

  resource :spending_info, path: :financials, only: [:show] do
    get :survey
    post :survey, action: :save_survey
  end

  resources :travel_plans do
    collection do
      patch :skip_survey
    end
  end

  # ---- ADMINS -----

  # This method is necessary to get the 'authenticate_admin!' method
  # in the controllers

  get 'admin/sign_in', to: 'admin_area/sessions#new', as: :new_admin_session
  post 'admin/sign_in', to: 'admin_area/sessions#create', as: :admin_session
  delete 'admin/sign_out', to: 'admin_area/sessions#destroy',
    as: :destroy_admin_session

  namespace :admin, module: :admin_area do
    resources :accounts, only: [:index] do
      collection do
        get :search
      end
      member do
        get :inspect
      end
    end
    resources :admins
    resources :banks, only: [:index]
    resources :card_products, except: :destroy do
      collection do
        get :images
      end
      resources :offers, only: [:index, :create, :new]
    end

    resources :card_accounts, only: [:edit, :update]
    resources :currencies

    # show and edit redirect to the nested action:
    resources :offers, only: [:show, :edit, :index, :update] do
      member do
        patch :kill, :replace, :unkill, :verify
      end
    end
    resources :destinations, only: :index
    Destination::TYPES.each do |type|
      # /airports, /cities, /countries, /regions
      get type.pluralize, to: "destinations##{type}"
    end
    resources :people, only: :show do
      resource :spending_info
      resources :card_accounts
      resources :card_recommendations, only: [:create, :edit, :update] do
        collection do
          post :complete
        end
      end
    end
    resources :card_recommendations
    resources :recommendation_notes, only: [:edit, :update]
    resources :recommendation_requests
    resource :registration
    resources :travel_plans, only: [:edit, :update]
  end

  # ---- /ADMINS -----
end

app/models/card/identifier.rb
# A short string that allows the admin to quickly identify the card.
# Format: AA-BBB-C.
# A: bank code - An integer (see below)
# B: card code - a 2-4 letter arbitrary code, set by the admin
# C: network code - if network is unknown, then '?'. Else 'A', 'M', or 'V', for
#                   Amex, MasterCard, or Visa respectively
#
class Card::Identifier
  attr_reader :identifier
  alias to_str identifier
  alias to_s   identifier

  def initialize(card)
    @card = card
    @bank = card.bank
    @identifier = [bank_code, card_code, network_code].join('-').freeze
  end

  def ==(other)
    identifier == other.to_str
  end

  def <=>(other)
    to_str <=> other.to_str
  end

  private

  # A 1-2 digit number which uniquely identifies both which bank the card belongs
  # to, and whether it is a business card or a personal one. this forms part of
  # the unique identifier for each card, which allows the admin to determine
  # these things about the card at a glance.
  #
  # The bank code is determined by the bank's id, which is always an odd number.
  # If this is a personal card, bank_number is equal to bank.id. If this is a
  # business card, bank_number is equal to bank.id + 1.
  #
  # (This numbering system is a legacy thing from before this app existed, when we
  # still doing everything through Fieldbook, Infusionsoft etc.)
  def bank_code
    '%.2d' % (@card.bp == "personal" ? @bank.personal_code : @bank.business_code)
  end

  def card_code
    @card.code
  end

  def network_code
    @card.network == "unknown_network" ? "?" : @card.network.upcase[0]
  end
end

app/models/card/product.rb
# A brand of Card offered by a particular bank, e.g. "Chase Sapphire". A
# specific instance of a card owned owned by a particular person (i.e. the one
# physical copy of a Chase Sapphire card which you keep in your wallet, as
# opposed to the general concept of a Chase Sapphire card), is represented by
# the Card model (which we plan on eventually renaming to just 'card')
class Card::Product < ApplicationRecord
  self.inheritance_column = :_no_sti

  # Attributes

  enum bp: [:business, :personal]

  enum network: {
    # can't call this 'unknown' as that would conflict with types
    unknown_network: 0,
    visa:            1,
    mastercard:      2,
    amex:            3,
  }
  enum type: {
    # can't call this 'unknown' as that would conflict with networks
    unknown_type: 0,
    credit:  1,
    charge:  2,
    debit:   3,
  }

  concerning :Image do
    included do
      # Standard credit card dimensions are 85.60*53.98mm, which gives the
      # following aspect ratio:
      ASPECT_RATIO = 1.586

      has_attached_file :image, styles: {
        large:  "350x#{350 / ASPECT_RATIO}>",
        medium: "210x#{210 / ASPECT_RATIO}>",
        small:  "140x#{140 / ASPECT_RATIO}>",
      }, default_url: "/images/:style/missing.png"
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
      validates_attachment_presence :image
    end
  end

  delegate :name, to: :bank, prefix: true

  def identifier
    Identifier.new(self)
  end

  def annual_fee
    annual_fee_cents / 100.0 unless annual_fee_cents.nil?
  end

  def annual_fee=(annual_fee_dollars)
    self.annual_fee_cents = (annual_fee_dollars.to_i * 100).to_i
  end

  # Validations

  validates :code, format: {
    message: "must consist only of capital letters and be 2-4 letters long",
    with: /\A[A-Z]{2,4}\z/,
  }
  with_options presence: true do
    validates :annual_fee_cents
    validates :bank_id
    validates :bp
    validates :name
    validates :network
    validates :type
  end

  # Associations

  has_many :offers
  has_many :cards
  belongs_to :currency
  belongs_to :bank

  # Scopes

  scope :survey, -> { where(shown_on_survey: true) }

  # Callbacks

  auto_strip_attributes :code, :name, callback: :before_validation

  def serializer_class
    Card::Product::Serializer
  end
end

app/controllers/admin/cards_controller.rb
module Admin
  class CardsController < AdminController

    # GET /admin/cards
    def index
      @cards = Card.order(:identifier)
    end

    # GET /admin/cards/1
    def show
      @card = get_card
    end

    # GET /admin/cards/new
    def new
      @card = Card.new
    end

    # GET /admin/cards/1/edit
    # Unimplemented
    # def edit
    #   @card = get_card
    # end

    # POST /admin/cards
    def create
      @card = Card.new(card_params)

      if @card.save
        flash[:success] = "Card was successfully created."
        redirect_to admin_cards_path
      else
        render :new
      end
    end

    # PATCH/PUT /admin/cards/1
    # Unimplemented
    # def update
    #   @card = get_card
    #   if @card.update(card_params)
    #       redirect_to @card, notice: 'Card was successfully updated.'
    #   else
    #     render :edit
    #   end
    # end

    # DELETE /admin/cards/1
    # def destroy
    #   @card = get_card
    #   @card.destroy
    #   redirect_to cards_url, notice: 'Card was successfully destroyed.'
    # end

    def active
      @card = get_card
      @card.toggle!(:active)
      respond_to do |f|
        f.js
      end
    end


    private

    def get_card
      Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(
        :identifier, :name, :brand, :bp, :type, :annual_fee
      )
    end

  end
end

app/controllers/cards_controller.rb
class CardsController < AuthenticatedUserController
  onboard :owner_cards, :companion_cards, with: [:survey, :save_survey]

  def index
    # Unfortunately I can't figure out a better way of avoiding all the N+1 issues
    # without reloading the current account, since you can't call `includes`
    # after the account has already been loaded.
    account = Account.includes(
      people: [:account, { card_accounts: :card_product },
               actionable_card_recommendations: [:card_product, { offer: { card_product: :currency } }],],
    ).find(current_account.id)
    if account.actionable_card_recommendations?
      cookies[:recommendation_timeout] = { value: "timeout", expires: 24.hours.from_now }
    end

    unless current_admin
      account.card_recommendations.unseen.update_all(seen_at: Time.zone.now)
    end

    render cell(Card::Cell::Index, account)
  end

  def survey
    @person = load_person
    redirect_if_onboarding_wrong_person_type! && return
    redirect_if_onboarding_wrong_person_type! && true
    form = Card::Survey.new(@person)
    render cell(Card::Cell::Survey, @person, form: form)
  end

  def save_survey
    @person = load_person
    redirect_if_onboarding_wrong_person_type! && return
    form = Card::Survey.new(@person)
    if form.validate(survey_params)
      # There's currently no way that survey_params can be invalid
      form.save
      redirect_to onboarding_survey_path
    else
      raise 'this should never happen!'
    end
  end

  private

  def load_person
    current_account.people.find(params[:person_id])
  end

  def survey_params
    # key will be nil if they clicked 'I don't have any cards'
    result = params[:cards_survey] || { cards: [] }
    # couldn't figure out how to filter out unopened cards from within the form
    # object, so I'm doing it at the controller level
    result[:cards].select! { |c| Types::Form::Bool.(c[:opened]) }
    result
  end
end

app/helpers/card/products_helper.rb
class Card < ApplicationRecord
  module ProductsHelper
    def card_bp_filter_check_box_tag(bp)
      klass =  :card_bp_filter
      id    =  :"#{klass}_#{bp}"
      label_tag id do
        check_box_tag(
          id,
          nil,
          true,
          class: klass,
          data: { key: :bp, value: bp },
        ) << raw("&nbsp;&nbsp#{bp.capitalize}")
      end
    end

    def options_for_card_network_select(selected_network)
      options_for_select(
        CardProduct.networks.map do |network, _|
          [t("activerecord.attributes.card_product.networks.#{network}"), network]
        end,
        selected_network,
      )
    end

    def options_for_card_type_select(selected_type)
      options_for_select(
        CardProduct.types.map do |type, _|
          [t("activerecord.attributes.card_product.types.#{type}"), type]
        end,
        selected_type,
      )
    end
  end
end

app/views/cards/index.html.erb
<% provide :title, "Your Cards" %>

<div class="hpanel">
  <div class="panel-heading hbuilt">
    <h1>My Recommendations</h1>
  </div><!-- panel-heading -->

  <div class="panel-body">
    <% if @account.people.any?(&:eligible?) %>
      <% if @any_recommendations %>
        <%= cell(CardRecommendation::Cell::Note, @newest_rec_note) if @newest_rec_note %>

        <p>
          Your recommendations will expire after two weeks. Please click “Find My Card”
          below and complete the application on the bank's website. If you
          decide not to apply for a card, please click “No Thanks”.
        </p>

        <hr />

        <%= cell(Card::Cell::Index::CardRecommendations, @account) %>
      <% else %>
        <div class="alert alert-info">
          The Abroaders team is hand selecting the ideal rewards cards
          based on your current points, travel plans and spending. We’ll
          let you know as soon as the card recommendations are ready to
          view.
        </div>
      <% end %>
    <% else # no eligible people %>
      <p><%= t("dashboard.account.ineligible.title") %></p>
      <p><%= t("dashboard.account.ineligible.message") %></p>
    <% end %>
  </div><!-- .panel-body -->
</div><!-- .hpanel -->

<%= cell(Card::Cell::Index::CardAccounts, @account) %>

app/views/cards/survey.html.erb
<% provide :title, "Survey - Cards" %>

<div class="hpanel">
  <div class="panel-heading hbuilt">
    <div class="row">
      <div class="col-xs-12">
        <h1><%= n "Your", @person %> Cards</h1>
      </div>
    </div><!-- .row -->
  </div><!-- .panel-heading.hbuilt -->

  <div id="card-survey-initial" class="panel-body">
    <p>
      Before we can recommend <%= n "you", @person %> a credit card to apply
      for, we need to know which cards <%= n "you", @person %> already
      <%= n "have", @person %>.
    </p>

    <p>
      <%= n "Have", @person %> <%= n "you", @person %>
      ever had a credit card that earns points or miles?
    </p>

    <p>
      For example, a card that earns airline frequent flyer miles when you use
      it. Or bank points, like Amex, Chase, SPG, Citi, or Capital one.
    </p>

    <div class="btn-group">
      <button id="card-survey-initial-yes-btn" class="btn btn-primary">
        Yes
      </button>

      <button id="card-survey-initial-no-btn" class="btn btn-default">
        No
      </button>
    </div>
  </div>

  <div id="card-survey-confirm-no" class="panel-body" style="display:none;">
    <p>
      <%= n "You", @person %> <%= n "have", @person %> never had a card that
      earns points or miles:
    </p>

    <%= form_tag survey_person_cards_path(@person) do %>
      <div class="btn-group">
        <%= submit_tag 'Confirm', class: 'btn btn-primary' %>
        <button id="card-survey-confirm-no-back-btn" class="btn btn-default">
          Back
        </button>
      </div>
    <% end %>
  </div>

  <div id="card-survey-main-header" style="display:none;" class="panel-body">
    <p>
      Please select <strong>all</strong> of the credit/debit cards below for
      which <%= n "you", @person %> <%= n "have", @person %>
      <strong>ever</strong> been the <strong>primary cardholder</strong>.
    </p>

    <p>
      "Primary cardholder" means that the credit card account was opened using
      your name and social security number. You are not considered a primary
      cardholder of a card if someone else adds you as an authorized user on
      their account.
    </p>

    <p>
      <strong>Only</strong> select cards for which <%= n "you", @person %>
      <%= n "are", @person %> or <%= n "were", @person %> the primary cardholder.
    </p>
  </div><!-- .panel-body -->
</div><!-- .hpanel -->

<div id="card-survey-main-body" class="card-survey-form-wrapper" style="display:none;">
  <%= form_tag survey_person_cards_path(@person) do %>
    <p class="helper-message">Click a bank's name to see the list of cards for that bank</p>
    <% @survey.each_section do |bank, products_grouped_by_bp| %>

      <div class="bank-section">

        <div class="collapse-header">
          <a data-toggle="collapse" href="#bank-collapse-<%= bank.id %>">
            <h2><%= bank.name.upcase %></h2>
          </a>
          <i class="fa fa-sort-desc collapse-header" aria-hidden="true"></i>
        </div>

        <div id="bank-collapse-<%= bank.id %>" class="panel-collapse collapse">
          <div id="bank_<%= bank.id %>_cards">

            <% products_grouped_by_bp.each do |bp, products| %>
              <div id="bank_<%= bank.id %>_<%= bp %>_cards">
                <h4><%= bp.capitalize %> Cards</h4>
                <div class="row">
                  <%= cell(CardProduct::Cell::Survey::Product, collection: products) %>
                </div>
              </div>
            <% end # cards_for_1_bank.group_by(&:bp).each %>

          </div>
        </div>
      </div>

    <% end %>

    <div class="row">
      <div class="col-xs-12">
        <button class="btn btn-lg btn-primary">
          <i class="fa fa-check" aria-hidden="true"></i>
          Save and continue
        </button>
      </div>
    </div>
  <% end %>
</div>