config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  root to: "application#dashboard"

  # Mount this at a hard-to-guess URL
  mount Resque::Server.new, at: "/resque-c08cb17ca6581cbcad1501a7da7e8579"

  # --- NON-LOGGED-IN USERS ---

  get :sign_up, to: "registrations#new"
  post :sign_up, to: "registrations#create", as: :account_registration
  get :sign_up,  to: "registrations#new", as: :new_account_registration

  get :sign_in, to: "sessions#new", as: :new_account_session
  post :sign_in, to: "sessions#create", as: :account_session
  delete :sign_out, to: "sessions#destroy", as: :destroy_account_session

  post 'accounts/password',     to: 'passwords#create', as: :account_password
  get 'accounts/password/new',  to: 'passwords#new',    as: :new_account_password
  get 'accounts/password/edit', to: 'passwords#edit',   as: :edit_account_password
  put   'accounts/password',    to: 'passwords#update'
  patch 'accounts/password',    to: 'passwords#update'

  # --- EVERYBODY ---

  resources :airports, only: [] do
    collection { get :typeahead }
  end

  Destination::TYPES.each do |type|
    # /airports, /cities, /countries, /regions
    get type.pluralize, to: "destinations##{type}"
  end

  post :support, to: 'support#support'

  controller :static_pages do
    get :privacy_policy
    get :terms_and_conditions
    get :contact_us
  end

  # --- LOGGED IN ACCOUNTS ---

  resource :account, only: [:edit, :update] do
    get  :type
    post :type, action: :submit_type
  end

  resources :balances

  resources :card_recommendations do
    member do
      get   :click
      patch :decline
    end
  end

  resources :card_accounts, except: :index
  resources :cards, only: :index

  get  "eligibility/survey", to: "eligibilities#survey", as: :survey_eligibility
  post "eligibility/survey", to: "eligibilities#save_survey"

  get "estimates/:from_code/:to_code/:type/:no_of_passengers", to: "estimates#get"

  namespace :integrations do
    get 'award_wallet/settings'
    namespace :award_wallet do
      get :callback
      get :poll
      get :sync
      get :syncing
      get :survey
      post :survey, action: :save_survey

      resources :owners, only: [] do
        member do
          patch :update_person
        end
      end

      resources :accounts
    end
  end

  get 'auth/facebook/callback', to: 'integrations/facebook#callback'

  resources :interest_regions, only: [], path: "regions_of_interest" do
    collection do
      get  :survey
      post :survey, action: :save_survey
    end
  end

  resources :home_airports do
    collection do
      get  :edit
      post :overwrite
      get  :survey
      post :survey, action: :save_survey
    end
  end

  resources :notifications, only: :show

  resources :people, only: [] do
    resources :balances, only: [] do
      collection do
        get  :survey
        post :survey, action: :save_survey
      end
    end
    resources :cards, only: [] do
      collection do
        get  :survey
        post :survey, action: :save_survey
      end
    end
    resource :spending_info, path: :spending, only: [:edit, :update] do
      member do
        patch :confirm
      end
    end
  end

  resource :phone_number, only: [:new, :create] do
    post :skip
  end

  resources :card_products, only: [] do
    resources :card_accounts, only: [:new, :create]
  end

  resource :readiness, only: [:edit, :update] do
    collection do
      get  :survey
      post :survey, action: :save_survey
    end
  end

  resource :recommendation_requests

  get :slack, to: "slack_invites#new"
  post "slack/invite", to: "slack_invites#create"

  resource :spending_info, path: :financials, only: [:show] do
    get :survey
    post :survey, action: :save_survey
  end

  resources :travel_plans do
    collection do
      patch :skip_survey
    end
  end

  # ---- ADMINS -----

  # This method is necessary to get the 'authenticate_admin!' method
  # in the controllers

  get 'admin/sign_in', to: 'admin_area/sessions#new', as: :new_admin_session
  post 'admin/sign_in', to: 'admin_area/sessions#create', as: :admin_session
  delete 'admin/sign_out', to: 'admin_area/sessions#destroy',
    as: :destroy_admin_session

  namespace :admin, module: :admin_area do
    resources :accounts, only: [:index] do
      collection do
        get :search
      end
      member do
        get :inspect
      end
    end
    resources :admins
    resources :banks, only: [:index]
    resources :card_products, except: :destroy do
      collection do
        get :images
      end
      resources :offers, only: [:index, :create, :new]
    end

    resources :card_accounts, only: [:edit, :update]
    resources :currencies

    # show and edit redirect to the nested action:
    resources :offers, only: [:show, :edit, :index, :update] do
      member do
        patch :kill, :replace, :unkill, :verify
      end
    end
    resources :destinations, only: :index
    Destination::TYPES.each do |type|
      # /airports, /cities, /countries, /regions
      get type.pluralize, to: "destinations##{type}"
    end
    resources :people, only: :show do
      resource :spending_info
      resources :card_accounts
      resources :card_recommendations, only: [:create, :edit, :update] do
        collection do
          post :complete
        end
      end
    end
    resources :card_recommendations
    resources :recommendation_notes, only: [:edit, :update]
    resources :recommendation_requests
    resource :registration
    resources :travel_plans, only: [:edit, :update]
  end

  # ---- /ADMINS -----
end

app/controllers/admin_area/accounts_controller.rb
module AdminArea
  class AccountsController < AdminController
    include Auth::Controllers::SignInOut

    # GET /admin/accounts
    def index
      accounts = Account.includes(
        people: :spending_info,
        owner: :spending_info,
        companion: :spending_info,
      ).order("email ASC")
      render cell(Accounts::Cell::Index, accounts, page: params[:page])
    end

    def search
      run Accounts::Search
      render cell(
        Accounts::Cell::Search,
        result['collection'],
        query: result['query'],
      )
    end

    def inspect
      if current_account
        flash[:error] = 'Already signed in as a user'
        redirect_to :back
      end

      account = Account.find(params[:id])
      sign_in(:account, account)
      redirect_to root_path
    end
  end
end

app/controllers/admin_area/admin_controller.rb
module AdminArea
  class AdminController < ::ApplicationController
    before_action :authenticate_admin!
    before_action :simultaneous_login!

    private

    # If an admin is currently using the 'log in as user' feature, they must
    # exit that user's account before they can go back to doing normal admin
    # functions
    def simultaneous_login!
      redirect_to root_path if current_admin && current_account
    end
  end
end

app/controllers/admin_area/admins_controller.rb
module AdminArea
  class AdminsController < AdminController
    def index
      admins = Admin.all.order(id: :asc)
      render cell(AdminArea::Admins::Cell::Index, admins)
    end

    def new
      run AdminArea::Admins::New
      render cell(AdminArea::Admins::Cell::New, @model, form: @form)
    end

    def create
      run AdminArea::Admins::Create do
        flash[:success] = 'Created admin!'
        redirect_to admin_admins_path
        return
      end
      render cell(AdminArea::Admins::Cell::New, @model, form: @form)
    end

    def edit
      run Admins::Edit
      render cell(Admins::Cell::Edit, @model, form: @form)
    end

    def update
      run Admins::Update do
        flash[:success] = 'Updated admin!'
        redirect_to admin_admins_path
        return
      end
      render cell(Admins::Cell::Edit, @model, form: @form)
    end
  end
end

app/controllers/admin_area/alliances_controller.rb
module AdminArea
  class AlliancesController < AdminController
    def index
      @alliances = Alliance
                   .order(name: :asc)
                   .paginate(page: params[:page], per_page: 50)
    end

    def new
      @alliance = NewAllianceForm.new
    end

    def create
      @alliance = NewAllianceForm.new(alliance_params)
      if @alliance.save
        redirect_to admin_alliances_path, notice: "Alliance '#{@alliance.name}' was successfully created."
      else
        render :new
      end
    end

    def edit
      @alliance = EditAllianceForm.find(params[:id])
    end

    def update
      @alliance = EditAllianceForm.find(params[:id])
      if @alliance.update(alliance_params)
        redirect_to admin_alliances_path, notice: "Alliance '#{@alliance.name}' was successfully updated."
      else
        render :edit
      end
    end

    def destroy
      alliance = Alliance.find(params[:id])
      alliance.destroy!
      redirect_to admin_alliances_path, notice: "Alliance '#{alliance.name}' was deleted."
    end

    private

    def alliance_params
      params.require(:alliance).permit(:name)
    end
  end
end

app/controllers/admin_area/banks_controller.rb
module AdminArea
  class BanksController < AdminController
    def index
      render cell(Banks::Cell::Index, Bank.alphabetical)
    end
  end
end

app/controllers/admin_area/card_accounts_controller.rb
module AdminArea
  class CardAccountsController < AdminController
    def new
      run CardAccounts::New
      render cell(CardAccounts::Cell::New, @model, form: @form)
    end

    def create
      run CardAccounts::Create do
        flash[:success] = 'Added card!'
        return redirect_to admin_person_path(@model.person)
      end
      render cell(CardAccounts::Cell::New, @model, form: @form)
    end

    def edit
      run CardAccounts::Edit
      @form.prepopulate!
      render cell(CardAccounts::Cell::Edit, @model, form: @form)
    end

    def update
      run CardAccounts::Update do
        flash[:success] = 'Updated card!'
        return redirect_to admin_person_path(@model.person)
      end
      render cell(CardAccounts::Cell::Edit, @model, form: @form)
    end
  end
end

app/controllers/admin_area/card_products_controller.rb
module AdminArea
  class CardProductsController < AdminController
    before_action :check_currencies!, if: -> { Rails.env.development? }

    # GET /admin/cards
    def index
      products = CardProduct.all.includes(:offers, :currency).sort_by(&:bank_id)
      render cell(CardProducts::Cell::Index, products)
    end

    # GET /admin/cards/1
    def show
      product = CardProduct.includes(:currency).find(params[:id])
      render cell(CardProducts::Cell::Show, product)
    end

    # GET /admin/cards/new
    def new
      run CardProducts::New
      render cell(CardProducts::Cell::New, @model, form: @form)
    end

    # POST /admin/cards
    def create
      run CardProducts::Create do
        flash[:success] = 'Card product was successfully created.'
        redirect_to admin_card_product_path(@model)
        return
      end
      render cell(CardProducts::Cell::New, @model, form: @form)
    end

    # GET /admin/cards/1/edit
    def edit
      run CardProducts::Edit
      render cell(CardProducts::Cell::Edit, @model, form: @form)
    end

    # PATCH/PUT /admin/cards/1
    def update
      run CardProducts::Update do
        flash[:success] = 'Card product was successfully updated.'
        redirect_to admin_card_product_path(@model)
        return
      end
      render cell(CardProducts::Cell::Edit, @model, form: @form)
    end

    def images
      render cell(CardProducts::Cell::Images, CardProduct.all)
    end

    private

    def check_currencies!
      raise "no Currencies in the database" unless Currency.any?
    end
  end
end

app/controllers/admin_area/card_recommendations_controller.rb
module AdminArea
  class CardRecommendationsController < AdminController
    def create
      run CardRecommendations::Create do
        respond_to(&:js)
        return
      end
      raise 'this should never happen!'
    end

    def edit
      run CardRecommendations::Edit
      render cell(CardRecommendations::Cell::Edit, @model, form: @form)
    end

    def update
      run CardRecommendations::Update do
        flash[:success] = 'Updated rec!'
        return redirect_to(
          if params[:redirect_to] == 'offer'
            admin_offer_path(@model.offer)
          else
            admin_person_path(@model.person)
          end,
        )
      end
      @form.prepopulate!
      render cell(CardRecommendations::Cell::Edit, @model, form: @form)
    end

    def destroy
      rec = Card.recommended.find(params[:id])
      rec.destroy
      flash[:success] = 'Deleted recommendation'
      redirect_back(fallback_location: admin_person_path(rec.person))
    end

    def complete
      run CardRecommendations::Complete do |result|
        flash[:success] = 'Recs done! Requests are now marked as resolved'
        redirect_to admin_person_path(result['person'])
        return
      end
      raise 'this should never happen!'
    end
  end
end

app/controllers/admin_area/currencies_controller.rb
module AdminArea
  class CurrenciesController < AdminController
    def index
      currencies = Currency.all.order(:name)
      render cell(Currencies::Cell::Index, currencies)
    end

    def new
      run Currencies::New
      render cell(Currencies::Cell::New, @model, form: @form)
    end

    def create
      run Currencies::Create do
        flash[:success] = 'Created new currency!'
        redirect_to admin_currencies_path
        return
      end
      render cell(Currencies::Cell::New, @model, form: @form)
    end

    def edit
      run Currencies::Edit
      render cell(Currencies::Cell::Edit, @model, form: @form)
    end

    def update
      run Currencies::Update do
        flash[:success] = 'Updated currency'
        redirect_to admin_currencies_path
        return
      end
      render cell(Currencies::Cell::Edit, @model, form: @form)
    end
  end
end

app/controllers/admin_area/destinations_controller.rb
module AdminArea
  class DestinationsController < AdminController
    def index
      destinations = load_destinations.all
      render cell(Destinations::Cell::Index, destinations, page: params[:page], page_type: 'destination')
    end

    Destination::TYPES.each do |type|
      define_method type do
        destinations = load_destinations.send(type)
        render cell(Destinations::Cell::Index, destinations, page_type: type)
      end
    end

    private

    def load_destinations
      Destination.includes(:parent).order('name ASC')
    end
  end
end

app/controllers/admin_area/offers_controller.rb
module AdminArea
  class OffersController < AdminController
    def index
      if params[:card_product_id]
        card_product = CardProduct.find(params[:card_product_id])
        offers = card_product.offers
      else
        offers = Offer.includes(:card_product)
      end
      render cell(Offers::Cell::Index, offers, card_product: card_product)
    end

    def show
      offer = Offer.find(params[:id])
      render cell(Offers::Cell::Show, offer)
    end

    def new
      run Offers::New
      render cell(Offers::Cell::New, @model, form: @form)
    end

    def create
      run Offers::Create do
        flash[:success] = 'Offer was successfully created.'
        redirect_to admin_offer_path(@model)
        return
      end
      render cell(Offers::Cell::New, @model, form: @form)
    end

    def edit
      run Offers::Edit do
        render cell(Offers::Cell::Edit, @model, form: @form)
        return
      end
      raise 'this should never happen!'
    end

    def update
      run Offers::Update do
        flash[:success] = 'Offer was successfully updated.'
        redirect_to admin_offer_path(@model)
        return
      end
      render cell(Offers::Cell::Edit, @model, form: @form)
    end

    def kill
      run Offers::Kill
      flash[:success] = 'Killed offer'
      redirect_to request.referer
    end

    def replace
      run Offers::Replace
      flash[:success] = 'Replace offer of active recs!'
      redirect_to admin_offer_path(@model)
    end

    def unkill
      offer = Offer.find(params[:id])
      offer.update!(killed_at: nil)
      flash[:success] = 'Offer is no longer dead'
      redirect_to admin_offer_path(offer)
    end

    def verify
      run Offers::Verify
      flash[:success] = 'Verified offer'
      redirect_to request.referer
    end
  end
end

app/controllers/admin_area/people_controller.rb
module AdminArea
  class PeopleController < AdminController
    # GET /admin/people/1
    def show
      person = Person.includes(
        card_accounts: :card_product,
        balances: :currency,
      ).find(params[:id])

      card_products = CardProduct.includes(
        :currency, :recommendable_offers,
      ).recommendable

      render cell(People::Cell::Show, person, card_products: card_products)
    end
  end
end

app/controllers/admin_area/recommendation_requests_controller.rb
module AdminArea
  class RecommendationRequestsController < AdminController
    def index
      # accounts with unresolved recs:
      accounts = Account\
                 .joins(:unresolved_recommendation_requests)\
                 .includes(
                   :unresolved_recommendation_requests,
                   owner: :unresolved_recommendation_request,
                   companion: :unresolved_recommendation_request,
                 ).sort_by do |a|
        [
          a.owner.unresolved_recommendation_request&.created_at,
          a.companion&.unresolved_recommendation_request&.created_at,
        ].compact.max
      end
      render cell(RecommendationRequests::Cell::Index, accounts)
    end
  end
end

app/views/admin_area/card_products/_form.html.erb
<%= form_for [:admin, card] do |f| %>

  <p>All fields are required</p>

  <div class="form-group">
    <%= f.label      :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label  :network %>
    <%= f.select :network, options_for_card_network_select(f.object.network) %>
  </div>

  <div class="form-group">
    <%= f.label :personal %>
    <%= f.check_box :personal %>
  </div>

  <div class="form-group">
    <%= f.label  :type %>
    <%= f.select :type, options_for_card_type_select(f.object.type) %>
  </div>

  <div class="form-group">
    <%= f.label  :currency_id %>
    <%= f.collection_select :currency_id, Currency.order("name ASC"), :id, :name, include_blank: "No currency" %>
  </div>

  <div class="form-group">
    <%= f.label :bank_id %>
    <%= f.collection_select :bank_id, Bank.alphabetical, :id, :name %>
  </div>

  <div class="form-group">
    <%= f.label :annual_fee %>
    <div class="input-group">
      <div class="input-group-addon">
        $
      </div>
      <%= f.number_field :annual_fee %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.label :shown_on_survey, "Ask about this card on the onboarding survey?" %>
    <%= f.check_box :shown_on_survey %>
  </div>

  <%= f.submit "Save Card Product", class: "btn btn-primary" %>

  &nbsp;&nbsp;

  <% if f.object.persisted? %>
    <%= link_to "Cancel", admin_card_product_path(f.object) %>
    |
  <% end %>
  <%= link_to "Show all cards", admin_card_products_path %>

<% end %>

app/views/admin_area/card_products/images.html.erb
<% provide :title, "Card Images" %>

<div class="hpanel">
  <div class="panel-heading hbuilt">
    <h1>Card Images</h1>
  </div>

  <div class="panel-body">
    <div class="table-responsive">
      <table
        id="admin_card_images_table"
        class="table table-striped"
        cellpadding="1"
        cellspacing="1"
      >
        <tbody>
          <% @products.each do |product| %>
            <tr id="card_product_<%= product.id %>">
              <td><%= product.bank_name %></td>
              <td><%= link_to product.name, admin_card_product_path(product) %></td>
              <td><%= cell(CardProduct::Cell::Network, product) %></td>
              <td><%= cell(CardProduct::Cell::Image, product) %></td>
            </tr>
          <% end # present_each %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="panel-footer">
    <%= pluralize @products.size, "card" %>
  </div>
</div>

app/views/admin_area/card_products/index.html.erb
<% provide :title, 'Card Products' %>

<div class="hpanel">
  <div class="panel-heading hbuilt">
    <h1 class="font-light m-b-xs">
      Card Products
    </h1>
    <%= link_to 'Add New', new_admin_card_product_path %>
  </div>

  <div class="panel-body">
    <div class="table-responsive">
      <table
        id="admin_cards_table"
        class="table table-striped"
        cellpadding="1"
        cellspacing="1"
      >
        <thead>
          <tr>
            <th>ID</th>
            <th>Bank</th>
            <th>Name</th>
            <th>Network</th>
            <th>Currency</th>
            <th>B/P</th>
            <th>Type</th>
            <th>Annual Fee</th>
            <th>On survey?</th>
            <th></th>
            <th class="card-offer-ctrls">Offers</th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
            <tr id="card_product_<%= product.id %>">
              <td><%= product.id %></td>
              <td><%= product.bank_name %></td>
              <td><%= link_to product.name, admin_card_product_path(product) %></td>
              <td><%= cell(CardProduct::Cell::Network, product) %></td>
              <td><%= product.currency&.name || 'Unknown' %></td>
              <td><%= product.bp %></td>
              <td><%= product.type %></td>
              <td><%= cell(CardProduct::Cell::AnnualFee, product) %></td>
              <td class="card_shown_on_survey">
                <% if product.shown_on_survey? %>
                  <i class="fa fa-check"> </i>
                <% end %>
              </td>
              <td>
                <%= link_to 'Edit', edit_admin_card_product_path(product) %>
              </td>
              <td class="card-offer-ctrls">
                <%= link_to 'View', admin_card_product_offers_path(product) %> |
                <%= link_to 'New', new_admin_card_product_offer_path(product) %>
              </td>
            </tr>
          <% end # present_each %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="panel-footer">
    <%= pluralize @products.size, "card" %>
  </div>
</div>